### ISSUE TITLE
Feature Request: Add minor faction Influence and states to system requests

### ISSUE THREAD

**Issue by EricJFisher** [SayakMukhopadhyay/elitebgs#162]
Hello, I currently have a situation report application that utilizes your APIs and want to be respectful to not spam your APIs any more than absolutely necessary. If you want to see what I'm doing here's a link [https://github.com/EricJFisher/BGSBuddy](https://github.com/EricJFisher/BGSBuddy)

One problem I'm currently dealing with is I've been using your EDDB API to get influence / state data to try and reduce the number of requests I need to make against your APIs, however; because of the nature of EDDB often that data is stale by comparison to the EliteBGS's API data, I want to remedy this without slamming your API with way more requests... (and hopefully reduce the requests I'm already making to your API)

Currently the only means I have to get influence and state data on all factions in systems my faction is present in and the status of stations/settlements there would be as follows:
 - Faction request for my faction (to update systems my faction is present in and get it's influence / state, and conflict information in each system)
 - System request for each system my faction is present in (To get a list of all the other factions present in that system)
 - Faction request for all factions in all systems my faction is present in (to get information about each faction's influence and states in all systems my faction is present in)
 - Station request for each system my faction is present in to get a list of all assets and who controls them

Needless to say this would ramp up to quite a large number of requests... Probably more than either of us want hitting your API.

This could be streamlined by doing one of two things:
1. Add minor faction influence, states, etc to the EliteBGS API faction request (or an alternative version of that request)
2. Add minor faction influence, states, etc to the EliteBGS API system request (or an alternative version of that request) 
*including station information in these requests would reduce the number of requests I need to make against your API a great deal as well.

**Comment by SayakMukhopadhyay** [comment]
The APIs are structured so as to have the lease backend processing per request. This is because the servers are able to handle lots of individual requests and maybe throttle or block during high load. But if a single request fetches a lot of data, then that becomes a problem for the server.

As such, I am sorry to say this, but what you are looking for is not available at the moment. Your best bet would be to make the multiple requests as you are thinking of.

I have an idea of having an alternative API which can query the db directly but that idea has not been set into motion yet. So, I will keep this issue open.

**Comment by SayakMukhopadhyay** [comment]
This is now available in V5 API
